language: rust
rust:
  - stable

script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]
    then
      rustup component add rustfmt
      cargo fmt --all -- --check
    fi
  - RUST_BACKTRACE=1 cargo build --verbose --all
  - RUST_BACKTRACE=1 cargo test --verbose --all